const ServicesList = [
  {
    name: "ChatBot",
    title: "ChatBot",
    text: "Um Chabot especializado em Amazônia Azul",
    active: true,
    image: "Chatbot.jpg",
    imageAlt: "Ilustração de um robô de conversa",
  },
  {
    name: "Reporter",
    title: "Robô jornalista",
    text: "Um robô que gera notícias sobre a Amazônia Azul",
    active: true,
    image: "RoboJornalista.jpeg",
    imageAlt: "Ilustração de um robô jornalista",
  },
  {
    name: "Wiki",
    title: "Wiki",
    text: "Uma wiki especializada em temas da Amazônia Azul",
    active: true,
    image: "Wiki.png",
    imageAlt: "Ilustração de um Wiki",
  },
  {
    name: "4",
    title: "4",
    text: "Um quarto serviço de exemplo",
    active: false,
    image: "exemplo.png",
    imageAlt: "*",
  },
  {
    name: "5",
    title: "5",
    text: "Um quinto serviço de exemplo",
    active: false,
    image: "exemplo.png",
    imageAlt: "*",
  },
  {
    name: "6",
    title: "6",
    text: "Um sexto serviço de exemplo",
    active: false,
    image: "exemplo.png",
    imageAlt: "*",
  },
  {
    name: "*",
    title: "*",
    text: "Um * serviço de exemplo",
    active: false,
    image: "exemplo.png",
    imageAlt: "*",
  },
];

export default ServicesList;
